baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "PaperCSS"
theme = "papercss"
googleAnalytics = ""

[privacy.disqus]
disable = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
dateFormat = "Jan 2, 2006"
navTitleLink = "/"

[[menu.nav]]
name = "Blog"
url = "/blog"
weight = 1

[[menu.nav]]
name = "Products"
url = "/product/"
weight = 2

[[menu.nav]]
name = "Public Domain"
url = "/PD/"
weight = 3


[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2

