baseURL = "https://modularsamples.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Modular Samples"
theme = "papercss"
googleAnalytics = ""
paginate = 8

[privacy.disqus]
disable = true

[taxonomies]
tag = "tags"


[imaging]
quality = 99

[params]
homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
dateFormat = "Jan 2, 2006"
navTitleLink = "/"



[[menu.nav]]
name = "Products"
url = "/samples/product/"
weight = 1

[[menu.nav]]
name = "Public Domain"
url = "/samples/PD/"
weight = 2

[[menu.nav]]
name = "Tools & Software"
url = "/samples/tools/"
weight = 3

[[menu.nav]]
name = "About"
url = "/about"
weight = 4

[[menu.nav]]
name = "Contact"
url = "mailto:modularsamples@gmail.com"
weight = 4

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4



